LongCare/Models/Resident/MaintainContactPersonViewModel.cs
using LongCare.Models.Composition;
using System.Collections.Generic;
using System.Web.Mvc;
namespace LongCare.Models.Resident
{
    public class MaintainContactPersonViewModel: ViewModelBased
    {
       public ContentInformation Content { get; set; }
        public ContactPersonInformation Person { get; set; }
        public ContactDataInformation Contact { get; set; }
        public IEnumerable<SelectListItem> GenderList { get; set; }
        public IEnumerable<SelectListItem> RelationshipList { get; set; }
        public override string IsRequired(string fieldName)
        {
            switch(fieldName)
            {
              
                case "RealName":
                case "Relationship":
                    return base.IsRequired(fieldName);
                default:
                    return string.Empty;
            }

           
        }
    }
}

LongCare/Models/Resident/MaintainResidentViewModel.cs
using LongCare.Models.Composition;
using System.Collections.Generic;
using System.Web.Mvc;
namespace LongCare.Models.Resident
{
    public class MaintainResidentViewModel : ViewModelBased
    {
       public ContentInformation Content { get; set; }
        public PersonInformation Person { get; set; }
        public ContactDataInformation Contact { get; set; }
        public IEnumerable<SelectListItem> GenderList { get; set; }
        public override string IsRequired(string fieldName)
        {
            switch(fieldName)
            {
                case "PersonID":
                case "RealName":
                case "Birthday":
                    return base.IsRequired(fieldName);
                default:
                    return string.Empty;
            }

           
        }
    }
}

LongCare/Controllers/ResidentController.cs
using LongCare.ModelHelper;
using LongCare.Models;
using LongCare.Models.Resident;
using LongCare.Services;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedModels;

namespace LongCare.Controllers
{
    public class ResidentController : SurfaceController
    {
       
        #region 住民資料維護
        public ActionResult RenderMaintainResidentForm(ViewModelBased m)
        {
            MaintainResidentViewModel model = ViewModelHelper.MapViewModelBased<MaintainResidentViewModel>(m);
            if (m.ContentId != null && m.ContentId.Value != 0)
            {
                IContent content = Services.ContentService.GetById(m.ContentId.Value);
                if (content.ContentType.Alias == Resident.ModelTypeAlias)
                {
                    model.Content = ViewModelHelper.MapToContent(content);
                    model.Contact = ViewModelHelper.MapToContactData(content);
                    model.Person = ViewModelHelper.MapToPerson(content);
                }
                model.MaintainType = EnumMaintainType.u;
            }
            else
            {  
                model.MaintainType = EnumMaintainType.c;
            }

            model.GenderList = GetEnumList.GenderList();
            return PartialView("MaintainResidentForm", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitMaintainResidentForm(MaintainResidentViewModel model)
        {

            if (!ModelState.IsValid) return CurrentUmbracoPage();
            string submitResult = string.Empty;
            MyNodeService _h = new MyNodeService(Services);
            IContent thisContent;
            switch (model.MaintainType)
            {
                case EnumMaintainType.c:
                    string nodeName =_h.GetNodeName(model.ParentId.Value, Resident.ModelTypeAlias, "R", 4);
                    thisContent = _h.GetChildNode(model.ParentId.Value, Resident.ModelTypeAlias, nodeName);
                    submitResult = "新增成功";
                    break;
                case EnumMaintainType.u:
                    thisContent = Services.ContentService.GetById(model.ContentId.Value);
                    submitResult = "更新成功";
                    break;
                default:
                    return CurrentUmbracoPage();
            }
            if(model.Content != null)
            {
                ViewModelHelper.MapFromContent(model.Content, ref thisContent);
            }
            if(model.Contact != null)
            {
                ViewModelHelper.MapFromContact(model.Contact, ref thisContent);
            }
            if(model.Person != null)
            {
                ViewModelHelper.MapFromPerson(model.Person, ref thisContent);
            }
           
            Services.ContentService.SaveAndPublish(thisContent);
            ViewData["submitResult"] = submitResult;
            return (model.ReturnPageId != null) ? RedirectToUmbracoPage(model.ReturnPageId.Value, "submitResult=" + submitResult) : RedirectToCurrentUmbracoPage("submitResult=" + submitResult);
        }

        #endregion
        #region 聯絡人資料維護
        public ActionResult RenderMaintainContactPersonForm(ViewModelBased m)
        {
            MaintainContactPersonViewModel model = ViewModelHelper.MapViewModelBased<MaintainContactPersonViewModel>(m);
            if (m.ContentId != null && m.ContentId.Value != 0)
            {
                IContent content = Services.ContentService.GetById(m.ContentId.Value);
                if (content.ContentType.Alias == ContactPerson.ModelTypeAlias)
                {
                    model.Content = ViewModelHelper.MapToContent(content);
                    model.Contact = ViewModelHelper.MapToContactData(content);
                    model.Person = ViewModelHelper.MapToContactPerson(content);
                }
                model.MaintainType = EnumMaintainType.u;
            }
            else
            {
                model.MaintainType = EnumMaintainType.c;
            }

            model.GenderList = GetEnumList.GenderList();
            model.RelationshipList = GetEnumList.RelationshipList();

            return PartialView("MaintainContactPersonForm", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitMaintainContactPersonForm(MaintainContactPersonViewModel model)
        {

            if (!ModelState.IsValid) return CurrentUmbracoPage();
            string submitResult = string.Empty;
            MyNodeService _h = new MyNodeService(Services);
            IContent thisContent;
            switch (model.MaintainType)
            {
                case EnumMaintainType.c:
                    string nodeName = _h.GetNodeName(model.ParentId.Value,  ContactPerson.ModelTypeAlias, true, 2);
                    thisContent = _h.GetChildNode(model.ParentId.Value, ContactPerson.ModelTypeAlias, nodeName);
                    submitResult = "新增成功";
                    break;
                case EnumMaintainType.u:
                    thisContent = Services.ContentService.GetById(model.ContentId.Value);
                    submitResult = "更新成功";
                    break;
                default:
                    return CurrentUmbracoPage();
            }
            if (model.Content != null)
            {
                ViewModelHelper.MapFromContent(model.Content, ref thisContent);
            }
            if (model.Contact != null)
            {
                ViewModelHelper.MapFromContact(model.Contact, ref thisContent);
            }
            if (model.Person != null)
            {
                ViewModelHelper.MapFromContactPerson(model.Person, ref thisContent);
            }

            Services.ContentService.SaveAndPublish(thisContent);

            return (model.ReturnPageId != null) ? RedirectToUmbracoPage(model.ReturnPageId.Value, "submitResult=" + submitResult) : RedirectToCurrentUmbracoPage("submitResult=" + submitResult);
        }

        #endregion

        #region 刪除
        public ActionResult DeleteContent(ViewModelBased model)
        {
            string submitResult = string.Empty;
            if(model.ContentId != 0)
            {
                var c = Services.ContentService.GetById(model.ContentId.Value);
                var result = Services.ContentService.Delete(c);
                if(result.Success)
                {
                    submitResult = "刪除成功";
                }
                else
                {
                    submitResult = "刪除失敗";
                }

            }
            return (model.ReturnPageId != null) ? RedirectToUmbracoPage(model.ReturnPageId.Value, "submitResult=" + submitResult) : RedirectToCurrentUmbracoPage("submitResult=" + submitResult);
        }
        #endregion
    }
}

LongCare/Views/Article.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    Html.RequiresCss("/css/Article-Clean.css");
}

@{ Html.RenderPartial("Content/_ArticleContent"); }

LongCare/Views/ArticleList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    Html.RequiresCss("/css/Article-List.css");
}

@{ Html.RenderPartial("Partials/Content/_LatestArticles"); }

LongCare/Views/Bed.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Bed>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}

LongCare/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresCss("/css/Contact-Form-Clean.css");
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js");
    Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js");
    Html.RequiresJs("/scripts/jquery.validate.min.js");
    Html.RequiresJs("/scripts/jquery.validate.unobtrusive.min.js");
    Html.RequiresJs("/scripts/jquery.unobtrusive-ajax.min.js");
    Html.RequiresJs("/scripts/contactForm.js");
}

<div class="contact-clean">
    @{ Html.RenderAction("RenderForm", "Contact"); }
</div>

LongCare/Views/Content.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    Html.RequiresCss("/css/Article-Clean.css");
}

@{ Html.RenderPartial("Content/_ArticleContent"); }

LongCare/Views/FacilityRoot.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.FacilityRoot>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}

LongCare/Views/Floor.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Floor>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
}

LongCare/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "master.cshtml";

}

<div class="container-fluid">
    <div class="row">
        @Html.Partial("SiteLayout/_TopNaviagtion")
    </div>
    <div class="row">
        <p class="mb-4">這是首頁</p>

        </div>

</div>

LongCare/Views/PrettyLink.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using Umbraco.Web.Models

@{
    Layout = null;

    var links = Model.Value<IEnumerable<Link>>("linkTarget");
    if (links != null && links.Any())
    {
        var prettyLink = links.FirstOrDefault();
        Response.RedirectPermanent(prettyLink.Url);
    }
}

LongCare/Views/Resident.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Resident>
@using ContentModels = Umbraco.Web.PublishedModels;
@*
    住民基本資料
*@
@{
    Layout = "masterLogin.cshtml";
    //聯絡人
    var contacts = Model.Children<ContactPerson>();

    //串接資訊
    var id = Request.QueryString["id"];                         //聯絡人
    var mode = Request.QueryString["mode"];                     //編修狀態
    var submitResult = Request.QueryString["submitResult"];     //編修結果

}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            @*顯示住民細項(包含聯絡人清單)*@
            @Html.Partial("Partials/Resident/_ShowResidentDetailCard", Model)
        </div>
    </div>
    <div class="row">
        @if (id != null)
        {
            var r = Umbraco.Content(id);
            <hr />
            if (mode == "u")
            {
                var model = new ViewModelBased
                {
                    ContentId = int.Parse(id),
                    ParentId = Model.Id,
                    ReturnPageId = Model.Id,
                    MaintainType = EnumMaintainType.u
                };
                <div class="col">
                    @*更新聯絡人*@
                    @Html.Action("RenderMaintainContactPersonForm", "Resident", model) 
                </div>
            }
            else
            {
                <div class="col">
                    @*顯示聯絡人細項*@
                    @Html.Partial("Partials/Resident/_ShowContactPersonDetailCard", r)
                </div>
                if (mode == "d")
                {
                    var model = new ViewModelBased
                    {
                        ContentId = int.Parse(id),
                        ParentId = Model.Id,
                        ReturnPageId = Model.Id,
                        MaintainType = EnumMaintainType.d
                    };
                    <div>
                        @*刪除聯絡人*@
                        @Html.ActionLink("確定要刪除?", "DeleteContent", "Resident", model, new { @class = "btn btn-primary" })
                    </div>
                }
            }
        }
        else if (mode != null && mode == "c")
        {
            @*若是要新增*@
            var model = new ViewModelBased
            {
                ParentId = Model.Id,
                ReturnPageId = Model.Id,
                MaintainType = EnumMaintainType.c

            };
            <hr />
            <div class="col">
                @*新增聯絡人*@
                @Html.Action("RenderMaintainContactPersonForm", "Resident", model)
            </div>
        }
    </div>
</div>

LongCare/Views/ResidentRoot.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ResidentRoot>
@using ContentModels = Umbraco.Web.PublishedModels;
@*
    住民管理系統首頁
*@
@{

    Layout = "masterLogin.cshtml";
    //列出所有住宿中的住民
    var residentList = Model.Children<Resident>();
    //取得傳入資料
    var id = Request.QueryString["id"];
    var mode = Request.QueryString["mode"];
    var submitResult = Request.QueryString["submitResult"];
}

<div class="container-fluid">
    <!--顯示住民清單-->
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">住民清單 <span class="float-right"><button href="?mode=c" title="新增" onclick="location.href='?mode=c'"><i class="fas fa-plus text-primary"></i></button></span></h5>
                </div>
                <div class="card-body">
                    @Html.Partial("Partials/Resident/_ShowResidentListTable", residentList)
                </div>
                @if (submitResult != null)
                {
                    <div class="card-footer">
                        <p>@submitResult</p>
                    </div>

                }
            </div>
        </div>
    </div>
    <div class="row mt-3">
        @*如果 rId有值, 表示要顯示詳細內容或者更新*@
        @if (id != null)
        {
            var r = Umbraco.Content(id);
            <hr />
            @*如果是要更新*@
            if (mode == "u")
            {
                var model = new ViewModelBased
                {
                    ContentId = int.Parse(id),
                    ParentId = Model.Id,
                    ReturnPageId = Model.Id,
                    MaintainType = EnumMaintainType.u
                };
                <div class="col">
                    @Html.Action("RenderMaintainResidentForm", "Resident", model)
                </div>

            }
            else
            {
                <div class="col">
                    @Html.Partial("Partials/Resident/_ShowResidentDetailCard", r)
                </div>
                if (mode == "d")
                {
                    var model = new ViewModelBased
                    {
                        ContentId = int.Parse(id),
                        ParentId = Model.Id,
                        ReturnPageId = Model.Id,
                        MaintainType = EnumMaintainType.d
                    };
                    <div>
                        @Html.ActionLink("確定要刪除?", "DeleteContent", "Resident", model, new { @class = "btn btn-primary" })
                    </div>

                }

            }

        }
        else if (mode != null && mode == "c")
        {
            @*若是要新增*@
            var model = new ViewModelBased
            {
                ParentId = Model.Id,
                ReturnPageId = Model.Id,
                MaintainType = EnumMaintainType.c

            };

            <hr />
            <div class="col">
                @Html.Action("RenderMaintainResidentForm", "Resident", model)
            </div>

        }
    </div>

</div>

@section scripts{
    <script>
        $(
            function () {
                $('#Person_Birthday').datepicker();
            });

    </script>
    <script>
        function Delete(id) {

        }
    </script>
}

LongCare/Views/Search.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@using ClientDependency.Core.Mvc

@{
    Layout = "Master.cshtml";
    Html.RequiresCss("/css/Contact-Form-Clean.css");
    var searchQuery = Request.QueryString["q"];
}

<div class="contact-clean">
    <form action="@Model.Url" method="GET" id="search">
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-8">
                    <input type="text" class="form-control col-xs-6" placeholder="Search..." name="q" value="@searchQuery" />
                </div>
                <div class="col-xs-12 col-sm-4">
                    <button class="btn btn-primary">Search <i class="fa fa-search"></i></button>
                </div>
                <div class="col-xs-12">
                    @if (!string.IsNullOrWhiteSpace(searchQuery))
                    {
                        var results = Umbraco.ContentQuery.Search(searchQuery, string.Empty);
                        long resultCount = results != null && results.Any() ? results.Count() : 0;
                        <div class="searchresults">
                            <p>We found <strong>@resultCount</strong> result@(resultCount != 1 ? "s" : "") when searching for <strong>@searchQuery</strong></p>
                            @if (resultCount > 0)
                            {
                                <ul>
                                    @foreach (var result in results)
                                    {
                                        <li>
                                            <h3><a href="@result.Content.Url">@result.Content.Name</a></h3>
                                            <p>@(result.Content.Value<string>("metaDescription"))</p>
                                        </li>
                                    }
                                </ul>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </form>
</div>

LongCare/Views/master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{ Html.RenderPartial("SiteLayout/_MetaData"); }

    <link href="~/node_modules/startbootstrap-sb-admin-2/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/node_modules/startbootstrap-sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
</head>
<body id="page-top">

    <div id="wrapper">
        <!--Sidebar-->
        @*  @Html.CachedPartial("SiteLayout/_MainNavigation", Model, 3600)*@
        @Html.Partial("SiteLayout/_MainNavigation", Model)
        <!--End of Sidebar-->
        <!--Content-->
        @RenderBody()
        <!--End of Sidebar-->
    </div>

    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/js/sb-admin-2.min.js"></script>
    <script src="~/node_modules/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/scripts/MyScripts.js"></script>
</body>
</html>

LongCare/Views/masterLogin.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{ Html.RenderPartial("SiteLayout/_MetaData"); }

    <link href="~/node_modules/startbootstrap-sb-admin-2/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/node_modules/startbootstrap-sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body id="page-top">
    <div id="wrapper">
        <!--Sidebar-->
        @*  @Html.CachedPartial("SiteLayout/_MainNavigation", Model, 3600)*@
        @Html.Partial("SiteLayout/_MainNavigation", Model)
        <!--End of Sidebar-->
        <!--Content-->
        <div class="container-fluid">
            <div class="row">
                @Html.Partial("SiteLayout/_TopNaviagtion")
            </div>
            <div class="row">
                @Html.Partial("SiteLayout/PageDeep")
                @RenderBody()
            </div>

        </div>
        <!--End of Sidebar-->
    </div>

    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/node_modules/startbootstrap-sb-admin-2/js/sb-admin-2.min.js"></script>
    <script src="~/node_modules/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/scripts/MyScripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>